### PR TITLE
support AAAA

### PR DESCRIPTION
**Pull request by othillo**
Hi, this PR adds the AAAA record type to react/dns.

### CODE REVIEW

**Comment by cboden** [comment]
Awesome!

**Comment by WyriHaximus** [comment]
IMHO we should add this 👍

**Comment by clue** [comment]
Awesome! Functionally LGTM – But the goal is a bit unclear from an integrators view point, given that I don't see this being used anywhere? How is (can) this used or is this only an internal preparation? Also, this only handles parsing incoming responses, but we never actually prepare any such outgoing requests afaict?

(Also applies to #59 afaict)

**Comment by asm89** [comment]
@clue We use an `Executor` directly. E.g. `$executor->query($server, new Query(...));`. Same for the PTR PR.

**Comment by clue** [comment]
@asm89 This is interesting! I don't see this covered anywhere in either the README, examples or functional tests, does it make sense to you to add functional/integration tests as part of this PR? :+1:

**Comment by asm89** [comment]
> @asm89 This is interesting! I don't see this covered anywhere in either the README, examples or functional tests

It's covered in the `ExecutorInterface` and it's how the `Resolver` uses the executor. Using the `Executor` directly does seem a bit like using an internal class at the moment. If you and other maintainers agree it would be great to see the interface to get advertised for more advanced use cases. The `Resolver` is quite limited at the moment. When resolving `A` records we for example want to get _all_ of them. This is only possible by bypassing the `Resolver`.

> does it make sense to you to add functional/integration tests as part of this PR?

I'd rather see it being done in a follow up. The parser code is unit tested. We do use the executor directly now and it seems to work fine. The library does not have any integration tests for the `Executor` it seems, only some unit tests that mock out the interactions with the `Parser`. That doesn't seem like to big of a deal as the executor takes care of the data connection part. The parser does the heavy lifting of parsing the response. Whatever the parser returns is directly returned through the API of the executor: https://github.com/reactphp/dns/blob/e09ca286e3e18fea93317315dd7fc59d7963af8a/src/Query/Executor.php#L113-L132.

**Comment by WyriHaximus** [comment]
> If you and other maintainers agree it would be great to see the interface to get advertised for more advanced use cases.

:+1: from me on that. Although that would be better suited in a different PR.

> > does it make sense to you to add functional/integration tests as part of this PR?

> I'd rather see it being done in a follow up.

Agreed, this fits perfectly in the way of small PR's we've been doing lately

**Comment by clue** [comment]
@asm89 Thanks for the background info! I was mostly curious as to how we should describe (*sell*) this feature in the README/CHANGELOG and I agree that it makes sense to get this in as-is :+1: A follow-up PR to document and test this "advanced usage" would be much appreciated :+1: 

Thanks for the high quality PR, LGTM! :shipit:

**Comment by othillo** [comment]
Thank you!

**Pull request merged**
