### PR TITLE
Use a CSPRNG for generating query IDs

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Build failure is unrelated to this PR

**Comment by kelunik** [comment]
Maybe just drop HHVM entirely?

**Comment by clue** [comment]
Thanks for filing this PR! I can see where you're coming from, but can you please give some background information on why you think we should get this in? Thanks!

**Comment by kelunik** [comment]
@clue Because it mitigates fake responses being accepted.

**Pull request closed without merging**
