### PR TITLE
Missing RR implementation & advanced usage

### PR DESCRIPTION
**Pull request by attozk**
* Added support for MX, TXT, PTR, SOA, ANY, NS, AAAA records
* Added additional & authority message parsers & dumper (includes RobinvdVleuten's https://github.com/reactphp/react/pull/272)
* Fixed TCP retry parser & dumper. In TCP first two octets describe the length of data
* Added explain method to Message, Query, Record for detailed information in a dig like format.
* Added examples
* Message->questions now stores array of Query objects instead of array of array

### CODE REVIEW

**Comment by attozk** [comment]
@igorw 
What are your thoughts about merging it at this point and tackling state mutation later on as you originally suggested.

**Comment by attozk** [comment]
@igorw , @cboden 

ping?

**Comment by WyriHaximus** [comment]
@clue Maybe something for you since you're also working on some more DNS PR's?

**Comment by clue** [comment]
This PR does in fact contain quite a bit of useful code that I'd love to see included! Though I agree with @igorw this is a bit hard to review given the amount of code changed. Ideally, this would be split up into several smaller PRs.

Either way, is there anything that can be done to move this forward?

**Comment by attozk** [comment]
I would love to see this merged. Is there anything you need from me at this point @clue

**Pull request closed without merging**
