### PR TITLE
First class support for PHP7 and HHVM

### PR DESCRIPTION
**Pull request by clue**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
LGTM :shipit:

**Comment by clue** [comment]
Will look into the build error on PHP7…

**Comment by WyriHaximus** [comment]
That's interesting, haven't seen this happen before to be honest. Take a look at [`vectorface/dunit`](https://github.com/Vectorface/dunit), using it in my own projects to test against multiple versions, and could make it easier to test PHP7 locally. (Needs docker though.)

**Comment by clue** [comment]
Resolved the build error by removing the affected test (pointless test to begin with).

**Pull request merged**
